/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    lifestyle: Lifestyle;
    branches: Branch;
    'branch-contact-pages': BranchContactPage;
    'branch-space-rental-pages': BranchSpaceRentalPage;
    blogs: Blog;
    vendors: Vendor;
    'whats-on': WhatsOn;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    lifestyle: LifestyleSelect<false> | LifestyleSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    'branch-contact-pages': BranchContactPagesSelect<false> | BranchContactPagesSelect<true>;
    'branch-space-rental-pages': BranchSpaceRentalPagesSelect<false> | BranchSpaceRentalPagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    'whats-on': WhatsOnSelect<false> | WhatsOnSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    contact: Contact;
    homepage: Homepage;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lifestyle".
 */
export interface Lifestyle {
  id: number;
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Branch identity and landing page content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact page per branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-contact-pages".
 */
export interface BranchContactPage {
  id: number;
  title: string;
  branch: number | Branch;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Space rental page per branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-space-rental-pages".
 */
export interface BranchSpaceRentalPage {
  id: number;
  title: string;
  branch: number | Branch;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  title: string;
  slug: string;
  branch: number | Branch;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Activities and listings shown on each branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on".
 */
export interface WhatsOn {
  id: number;
  title: string;
  slug: string;
  branch: number | Branch;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'lifestyle';
        value: number | Lifestyle;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'branch-contact-pages';
        value: number | BranchContactPage;
      } | null)
    | ({
        relationTo: 'branch-space-rental-pages';
        value: number | BranchSpaceRentalPage;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'whats-on';
        value: number | WhatsOn;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lifestyle_select".
 */
export interface LifestyleSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-contact-pages_select".
 */
export interface BranchContactPagesSelect<T extends boolean = true> {
  title?: T;
  branch?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-space-rental-pages_select".
 */
export interface BranchSpaceRentalPagesSelect<T extends boolean = true> {
  title?: T;
  branch?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  branch?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on_select".
 */
export interface WhatsOnSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  branch?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero?: {
    title?: string | null;
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
  };
  info?:
    | {
        hexCode?: string | null;
        richTextEditor?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  awards?: {
    media?:
      | {
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  kinnestMarquee?: {
    media?:
      | {
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  contactSubject?: string[] | null;
  accordion?:
    | (
        | {
            title?: string | null;
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doubleColumn';
          }
        | {
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleColumn';
          }
      )[]
    | null;
  email?: string | null;
  tel?: string | null;
  kinnestGroup?: string | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    line?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
    title?: string | null;
  };
  motto?:
    | {
        text?: string | null;
        shape?: ('hexagon' | 'circle' | 'square') | null;
        id?: string | null;
      }[]
    | null;
  about?: {
    title?: string | null;
    description?: string | null;
    stickyNotes?:
      | {
          shape?: ('square' | 'circle' | 'heart') | null;
          /**
           * Use a design system hex code, e.g. #FFFFFF.
           */
          hexCode?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  peopleOfTheCommons?: {
    title?: string | null;
    cards?:
      | {
          media?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  flexibleSectionShow?: boolean | null;
  flexibleSection?:
    | {
        title?: string | null;
        description?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  recommender?: {
    title?: string | null;
    suffix?: string | null;
    lifestyles?: (number | Lifestyle)[] | null;
  };
  membership?: {
    title?: string | null;
    description?: string | null;
    button?: {
      text?: string | null;
      link?: string | null;
    };
    cardMedia?:
      | {
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  bingo?: {
    title?: string | null;
    grid?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
      };
  info?:
    | T
    | {
        hexCode?: T;
        richTextEditor?: T;
        media?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        media?:
          | T
          | {
              media?: T;
              id?: T;
            };
      };
  kinnestMarquee?:
    | T
    | {
        media?:
          | T
          | {
              media?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  contactSubject?: T;
  accordion?:
    | T
    | {
        doubleColumn?:
          | T
          | {
              title?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        singleColumn?:
          | T
          | {
              richText?: T;
              id?: T;
              blockName?: T;
            };
      };
  email?: T;
  tel?: T;
  kinnestGroup?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        line?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
        title?: T;
      };
  motto?:
    | T
    | {
        text?: T;
        shape?: T;
        id?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
        stickyNotes?:
          | T
          | {
              shape?: T;
              hexCode?: T;
              id?: T;
            };
      };
  peopleOfTheCommons?:
    | T
    | {
        title?: T;
        cards?:
          | T
          | {
              media?: T;
              title?: T;
              description?: T;
              link?: T;
              id?: T;
            };
      };
  flexibleSectionShow?: T;
  flexibleSection?:
    | T
    | {
        title?: T;
        description?: T;
        media?: T;
        id?: T;
      };
  recommender?:
    | T
    | {
        title?: T;
        suffix?: T;
        lifestyles?: T;
      };
  membership?:
    | T
    | {
        title?: T;
        description?: T;
        button?:
          | T
          | {
              text?: T;
              link?: T;
            };
        cardMedia?:
          | T
          | {
              media?: T;
              id?: T;
            };
      };
  bingo?:
    | T
    | {
        title?: T;
        grid?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}