/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    branches: Branch;
    'branch-contact-pages': BranchContactPage;
    'branch-venue-rental-pages': BranchVenueRentalPage;
    'branch-vendor-pages': BranchVendorPage;
    'branch-whats-on-pages': BranchWhatsOnPage;
    blogs: Blog;
    vendors: Vendor;
    'whats-on': WhatsOn;
    lifestyle: Lifestyle;
    'vendor-categories': VendorCategory;
    'whats-on-main-tags': WhatsOnMainTag;
    'whats-on-sub-tags': WhatsOnSubTag;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    'branch-contact-pages': BranchContactPagesSelect<false> | BranchContactPagesSelect<true>;
    'branch-venue-rental-pages': BranchVenueRentalPagesSelect<false> | BranchVenueRentalPagesSelect<true>;
    'branch-vendor-pages': BranchVendorPagesSelect<false> | BranchVendorPagesSelect<true>;
    'branch-whats-on-pages': BranchWhatsOnPagesSelect<false> | BranchWhatsOnPagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    'whats-on': WhatsOnSelect<false> | WhatsOnSelect<true>;
    lifestyle: LifestyleSelect<false> | LifestyleSelect<true>;
    'vendor-categories': VendorCategoriesSelect<false> | VendorCategoriesSelect<true>;
    'whats-on-main-tags': WhatsOnMainTagsSelect<false> | WhatsOnMainTagsSelect<true>;
    'whats-on-sub-tags': WhatsOnSubTagsSelect<false> | WhatsOnSubTagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    'blog-page': BlogPage;
    contact: Contact;
    homepage: Homepage;
    'privacy-policy': PrivacyPolicy;
    'venue-rental-page': VenueRentalPage;
    'vendors-page': VendorsPage;
    'whats-on-page': WhatsOnPage;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'venue-rental-page': VenueRentalPageSelect<false> | VenueRentalPageSelect<true>;
    'vendors-page': VendorsPageSelect<false> | VendorsPageSelect<true>;
    'whats-on-page': WhatsOnPageSelect<false> | WhatsOnPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Branch identity and landing page content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  tel?: string | null;
  floors?:
    | {
        floorId: string;
        text: string;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  primaryColor?: string | null;
  bgColor?: string | null;
  footerBg?: string | null;
  footerColor?: string | null;
  findUs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  openingHours?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parkingOptions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: {
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
    title?: string | null;
  };
  about?: {
    bgColor?: string | null;
    /**
     * Words are fixed per branch slug. Fill in media, title, and description for each word below.
     */
    wordGroups?:
      | {
          word: string;
          media?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  vibesCheck?: {
    title?: string | null;
    titleColor?: string | null;
    titleBgColor?: string | null;
    primaryColor?: string | null;
    secondaryColor?: string | null;
    gallery?:
      | {
          title?: string | null;
          day?: {
            media?: (number | null) | Media;
            mediaMobile?: (number | null) | Media;
          };
          night?: {
            media?: (number | null) | Media;
            mediaMobile?: (number | null) | Media;
          };
          id?: string | null;
        }[]
      | null;
  };
  vendorsSection?: {
    title?: string | null;
    displayType?: ('latest' | 'highlight') | null;
    /**
     * Manually select up to 3 vendors. Only vendors from this branch are shown.
     */
    highlightVendors?: (number | Vendor)[] | null;
  };
  whatsOnSection?: {
    title?: string | null;
    displayType?: ('latest' | 'highlight') | null;
    /**
     * Manually select up to 3 items. Only active items linked to this branch are shown.
     */
    highlightWhatsOn?: (number | WhatsOn)[] | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  /**
   * Recommended aspect ratio: 1
   */
  media?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  name: string;
  slug: string;
  branch: number | Branch;
  /**
   * Options are loaded from the selected branch’s floors.
   */
  floor?: string | null;
  /**
   * The lot number of the vendor on the floor.
   */
  lotNumber?: number | null;
  /**
   * Select up to 2 categories.
   */
  category?: (number | VendorCategory)[] | null;
  lifestyles?: (number | Lifestyle)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | (
        | 'vegan-option'
        | 'dairy-free-option'
        | 'vegetarian-option'
        | 'halal-friendly'
        | 'party-size'
        | 'only-at-the-commons'
      )[]
    | null;
  openingHours?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The format should be +66XXXXXXXXX
   */
  tel?: string[] | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    grab?: string | null;
    website?: string | null;
  };
  moreAt?:
    | {
        text?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-categories".
 */
export interface VendorCategory {
  id: number;
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lifestyle".
 */
export interface Lifestyle {
  id: number;
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Activities and listings shown on each branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on".
 */
export interface WhatsOn {
  id: number;
  branch: (number | Branch)[];
  title: string;
  slug: string;
  /**
   * Set the location for each selected branch.
   */
  branchLocations?: {
    thonglor?: string | null;
    saladaeng?: string | null;
    cloud11?: string | null;
  };
  dateToBeArchived?: string | null;
  /**
   * Recommended aspect ratio: 4 / 5
   */
  media?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  bgColor?: string | null;
  /**
   * Pick dates for filtering and display. Patterns: single, range, multiple dates, multiple date ranges (e.g. Thu 21 – Sat 23 Sep 26, Mon 28 – Wed 30 Sep 26).
   */
  eventSchedule: {
    pattern: 'single' | 'range' | 'multiple' | 'multiple-range';
    date?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    dates?:
      | {
          date: string;
          id?: string | null;
        }[]
      | null;
    ranges?:
      | {
          startDate: string;
          endDate: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Auto-generated from Event Schedule on save.
   */
  date?: string | null;
  time?: string | null;
  mainTag?: (number | null) | WhatsOnMainTag;
  subTags?: (number | WhatsOnSubTag)[] | null;
  highlightText?: {
    enabled?: boolean | null;
    text?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on-main-tags".
 */
export interface WhatsOnMainTag {
  id: number;
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on-sub-tags".
 */
export interface WhatsOnSubTag {
  id: number;
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact page per branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-contact-pages".
 */
export interface BranchContactPage {
  id: number;
  title: string;
  branch: number | Branch;
  contactBg?: (number | null) | Media;
  contactBgMobile?: (number | null) | Media;
  contactSubject?: string[] | null;
  accordion?:
    | (
        | {
            title?: string | null;
            columns?:
              | {
                  title?: string | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doubleColumn';
          }
        | {
            title?: string | null;
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttonText?: string | null;
            link?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleColumn';
          }
      )[]
    | null;
  email?: string | null;
  tel?: string | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    line?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Venue rental page per branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-venue-rental-pages".
 */
export interface BranchVenueRentalPage {
  id: number;
  branch: number | Branch;
  branchName?: string | null;
  bookingCta?: {
    type?: ('form' | 'linkout') | null;
    formSelectedButtonBgColor?: string | null;
    formSelectedButtonTextColor?: string | null;
    formSubmitButtonBgColor?: string | null;
    /**
     * If enabled, the form submit button text will be white on hover. Cannot be selected with dark brown hover text.
     */
    formSubmitWhiteTextOnHover?: boolean | null;
    /**
     * If enabled, the form submit button text will be dark brown on hover. Cannot be selected with white hover text.
     */
    formSubmitDarkBrownTextOnHover?: boolean | null;
    linkoutDescription?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    linkoutButtonBgColor?: string | null;
    linkoutButtonText?: string | null;
    linkoutButtonLink?: string | null;
    /**
     * If enabled, the button text will be white on hover.
     */
    linkoutButtonWhiteTextOnHover?: boolean | null;
  };
  title: string;
  landingMedia?: {
    desktop?: (number | null) | Media;
    mobile?: (number | null) | Media;
  };
  venuePackage?: {
    type?: ('pdf' | 'link') | null;
    pdf?: (number | null) | Media;
    link?: string | null;
  };
  venues?:
    | {
        /**
         * If enabled, the venue will be shown on the page.
         */
        show?: boolean | null;
        title?: string | null;
        formOptionName?: string | null;
        buttonBgColor?: string | null;
        buttonTextColor?: string | null;
        mediaGallery?: (number | Media)[] | null;
        amenitiesDescription?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        venueDescription?:
          | {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        information?: {
          area?: string | null;
          numberOfPeople?: string | null;
        };
        venueAmenities?:
          | {
              icon?:
                | (
                    | 'wifi'
                    | 'tv'
                    | 'microphone'
                    | 'white-board'
                    | 'bluetooth-speaker'
                    | 'sound-proof-panel'
                    | 'ac'
                    | 'fans'
                    | 'power-outlet'
                    | 'parking'
                    | 'coffee-machine'
                    | 'microwave'
                    | 'utensil'
                    | 'mixer'
                    | 'bakery'
                    | 'fridge'
                    | 'oven'
                    | 'mats'
                    | 'foldable-table'
                    | 'stool'
                    | 'camping-chair'
                    | 'calendar'
                    | 'clock'
                    | 'phone'
                  )
                | null;
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        otherAmenities?:
          | {
              icon?:
                | (
                    | 'wifi'
                    | 'tv'
                    | 'microphone'
                    | 'white-board'
                    | 'bluetooth-speaker'
                    | 'sound-proof-panel'
                    | 'ac'
                    | 'fans'
                    | 'power-outlet'
                    | 'parking'
                    | 'coffee-machine'
                    | 'microwave'
                    | 'utensil'
                    | 'mixer'
                    | 'bakery'
                    | 'fridge'
                    | 'oven'
                    | 'mats'
                    | 'foldable-table'
                    | 'stool'
                    | 'camping-chair'
                    | 'calendar'
                    | 'clock'
                    | 'phone'
                  )
                | null;
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        additionalFee?:
          | {
              icon?:
                | (
                    | 'wifi'
                    | 'tv'
                    | 'microphone'
                    | 'white-board'
                    | 'bluetooth-speaker'
                    | 'sound-proof-panel'
                    | 'ac'
                    | 'fans'
                    | 'power-outlet'
                    | 'parking'
                    | 'coffee-machine'
                    | 'microwave'
                    | 'utensil'
                    | 'mixer'
                    | 'bakery'
                    | 'fridge'
                    | 'oven'
                    | 'mats'
                    | 'foldable-table'
                    | 'stool'
                    | 'camping-chair'
                    | 'calendar'
                    | 'clock'
                    | 'phone'
                  )
                | null;
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        staffFee?: {
          title?: string | null;
          info?:
            | {
                title?: string | null;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        cta?: {
          ctaText?: string | null;
          ctaLink?: string | null;
          buttonBgColor?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  rate?: {
    title?: string | null;
    description?: string | null;
    backgroundColor?: string | null;
    textColor?: string | null;
    cnt?: {
      title?: string | null;
      /**
       * Row labels. Each column below gets one cell per row label, in the same order.
       */
      rows?: string[] | null;
      cols?:
        | {
            title?: string | null;
            /**
             * Cells are generated automatically from row labels above.
             */
            cells?:
              | {
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  promo?: {
    title?: string | null;
    description?: string | null;
    backgroundColor?: string | null;
    textColor?: string | null;
    cnt?: {
      title?: string | null;
      /**
       * Row labels. Each column below gets one cell per row label, in the same order.
       */
      rows?: string[] | null;
      cols?:
        | {
            title?: string | null;
            /**
             * Cells are generated automatically from row labels above.
             */
            cells?:
              | {
                  value?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Vendors page per branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-vendor-pages".
 */
export interface BranchVendorPage {
  id: number;
  title: string;
  branch: number | Branch;
  defaultMapTileColor?: string | null;
  activeMapTileColor?: string | null;
  pinColor?: string | null;
  backgroundColor?: string | null;
  textColor?: string | null;
  deliveryTitle?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  grabLink?: string | null;
  linemanLink?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * What's On page per branch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-whats-on-pages".
 */
export interface BranchWhatsOnPage {
  id: number;
  title: string;
  branch: number | Branch;
  landing?: {
    title?: string | null;
    cards?:
      | {
          background?: string | null;
          pattern?: ('zig-zag' | 'pill') | null;
          front?: {
            title?: string | null;
          };
          back?: {
            title?: string | null;
            description?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  latest?: {
    title?: string | null;
    background?: string | null;
    allBranchesBackground?: string | null;
  };
  dailyLiveMusic?: {
    title?: string | null;
    /**
     * Recommended aspect ratio: 0.8 (4 / 5)
     */
    images?: (number | Media)[] | null;
  };
  club?: {
    title?: string | null;
    mainTag?: (number | null) | WhatsOnMainTag;
  };
  allEventsAndWorkshops?: {
    title?: string | null;
    mainTag?: (number | WhatsOnMainTag)[] | null;
    background?: string | null;
    eventArchiveBackground?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  branch?: (number | Branch)[] | null;
  title: string;
  slug: string;
  /**
   * Set the location for each selected branch.
   */
  branchLocations?: {
    thonglor?: string | null;
    saladaeng?: string | null;
    cloud11?: string | null;
  };
  publishedDate?: string | null;
  dateToBeArchived?: string | null;
  /**
   * Recommended aspect ratio: 4 / 5
   */
  media?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'branch-contact-pages';
        value: number | BranchContactPage;
      } | null)
    | ({
        relationTo: 'branch-venue-rental-pages';
        value: number | BranchVenueRentalPage;
      } | null)
    | ({
        relationTo: 'branch-vendor-pages';
        value: number | BranchVendorPage;
      } | null)
    | ({
        relationTo: 'branch-whats-on-pages';
        value: number | BranchWhatsOnPage;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'whats-on';
        value: number | WhatsOn;
      } | null)
    | ({
        relationTo: 'lifestyle';
        value: number | Lifestyle;
      } | null)
    | ({
        relationTo: 'vendor-categories';
        value: number | VendorCategory;
      } | null)
    | ({
        relationTo: 'whats-on-main-tags';
        value: number | WhatsOnMainTag;
      } | null)
    | ({
        relationTo: 'whats-on-sub-tags';
        value: number | WhatsOnSubTag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  tel?: T;
  floors?:
    | T
    | {
        floorId?: T;
        text?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  primaryColor?: T;
  bgColor?: T;
  footerBg?: T;
  footerColor?: T;
  findUs?: T;
  openingHours?: T;
  parkingOptions?: T;
  hero?:
    | T
    | {
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
        title?: T;
      };
  about?:
    | T
    | {
        bgColor?: T;
        wordGroups?:
          | T
          | {
              word?: T;
              media?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  vibesCheck?:
    | T
    | {
        title?: T;
        titleColor?: T;
        titleBgColor?: T;
        primaryColor?: T;
        secondaryColor?: T;
        gallery?:
          | T
          | {
              title?: T;
              day?:
                | T
                | {
                    media?: T;
                    mediaMobile?: T;
                  };
              night?:
                | T
                | {
                    media?: T;
                    mediaMobile?: T;
                  };
              id?: T;
            };
      };
  vendorsSection?:
    | T
    | {
        title?: T;
        displayType?: T;
        highlightVendors?: T;
      };
  whatsOnSection?:
    | T
    | {
        title?: T;
        displayType?: T;
        highlightWhatsOn?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-contact-pages_select".
 */
export interface BranchContactPagesSelect<T extends boolean = true> {
  title?: T;
  branch?: T;
  contactBg?: T;
  contactBgMobile?: T;
  contactSubject?: T;
  accordion?:
    | T
    | {
        doubleColumn?:
          | T
          | {
              title?: T;
              columns?:
                | T
                | {
                    title?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        singleColumn?:
          | T
          | {
              title?: T;
              richText?: T;
              buttonText?: T;
              link?: T;
              id?: T;
              blockName?: T;
            };
      };
  email?: T;
  tel?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        line?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-venue-rental-pages_select".
 */
export interface BranchVenueRentalPagesSelect<T extends boolean = true> {
  branch?: T;
  branchName?: T;
  bookingCta?:
    | T
    | {
        type?: T;
        formSelectedButtonBgColor?: T;
        formSelectedButtonTextColor?: T;
        formSubmitButtonBgColor?: T;
        formSubmitWhiteTextOnHover?: T;
        formSubmitDarkBrownTextOnHover?: T;
        linkoutDescription?: T;
        linkoutButtonBgColor?: T;
        linkoutButtonText?: T;
        linkoutButtonLink?: T;
        linkoutButtonWhiteTextOnHover?: T;
      };
  title?: T;
  landingMedia?:
    | T
    | {
        desktop?: T;
        mobile?: T;
      };
  venuePackage?:
    | T
    | {
        type?: T;
        pdf?: T;
        link?: T;
      };
  venues?:
    | T
    | {
        show?: T;
        title?: T;
        formOptionName?: T;
        buttonBgColor?: T;
        buttonTextColor?: T;
        mediaGallery?: T;
        amenitiesDescription?: T;
        venueDescription?:
          | T
          | {
              content?: T;
              id?: T;
            };
        information?:
          | T
          | {
              area?: T;
              numberOfPeople?: T;
            };
        venueAmenities?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        otherAmenities?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        additionalFee?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        staffFee?:
          | T
          | {
              title?: T;
              info?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
        cta?:
          | T
          | {
              ctaText?: T;
              ctaLink?: T;
              buttonBgColor?: T;
            };
        id?: T;
      };
  rate?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundColor?: T;
        textColor?: T;
        cnt?:
          | T
          | {
              title?: T;
              rows?: T;
              cols?:
                | T
                | {
                    title?: T;
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
      };
  promo?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundColor?: T;
        textColor?: T;
        cnt?:
          | T
          | {
              title?: T;
              rows?: T;
              cols?:
                | T
                | {
                    title?: T;
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-vendor-pages_select".
 */
export interface BranchVendorPagesSelect<T extends boolean = true> {
  title?: T;
  branch?: T;
  defaultMapTileColor?: T;
  activeMapTileColor?: T;
  pinColor?: T;
  backgroundColor?: T;
  textColor?: T;
  deliveryTitle?: T;
  content?: T;
  grabLink?: T;
  linemanLink?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branch-whats-on-pages_select".
 */
export interface BranchWhatsOnPagesSelect<T extends boolean = true> {
  title?: T;
  branch?: T;
  landing?:
    | T
    | {
        title?: T;
        cards?:
          | T
          | {
              background?: T;
              pattern?: T;
              front?:
                | T
                | {
                    title?: T;
                  };
              back?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              id?: T;
            };
      };
  latest?:
    | T
    | {
        title?: T;
        background?: T;
        allBranchesBackground?: T;
      };
  dailyLiveMusic?:
    | T
    | {
        title?: T;
        images?: T;
      };
  club?:
    | T
    | {
        title?: T;
        mainTag?: T;
      };
  allEventsAndWorkshops?:
    | T
    | {
        title?: T;
        mainTag?: T;
        background?: T;
        eventArchiveBackground?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  branch?: T;
  title?: T;
  slug?: T;
  branchLocations?:
    | T
    | {
        thonglor?: T;
        saladaeng?: T;
        cloud11?: T;
      };
  publishedDate?: T;
  dateToBeArchived?: T;
  media?: T;
  gallery?: T;
  content?: T;
  buttonText?: T;
  buttonLink?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  media?: T;
  gallery?: T;
  name?: T;
  slug?: T;
  branch?: T;
  floor?: T;
  lotNumber?: T;
  category?: T;
  lifestyles?: T;
  description?: T;
  tags?: T;
  openingHours?: T;
  tel?: T;
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        grab?: T;
        website?: T;
      };
  moreAt?:
    | T
    | {
        text?: T;
        link?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on_select".
 */
export interface WhatsOnSelect<T extends boolean = true> {
  branch?: T;
  title?: T;
  slug?: T;
  branchLocations?:
    | T
    | {
        thonglor?: T;
        saladaeng?: T;
        cloud11?: T;
      };
  dateToBeArchived?: T;
  media?: T;
  gallery?: T;
  bgColor?: T;
  eventSchedule?:
    | T
    | {
        pattern?: T;
        date?: T;
        startDate?: T;
        endDate?: T;
        dates?:
          | T
          | {
              date?: T;
              id?: T;
            };
        ranges?:
          | T
          | {
              startDate?: T;
              endDate?: T;
              id?: T;
            };
      };
  date?: T;
  time?: T;
  mainTag?: T;
  subTags?: T;
  highlightText?:
    | T
    | {
        enabled?: T;
        text?: T;
      };
  content?: T;
  buttonText?: T;
  buttonLink?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lifestyle_select".
 */
export interface LifestyleSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-categories_select".
 */
export interface VendorCategoriesSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on-main-tags_select".
 */
export interface WhatsOnMainTagsSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on-sub-tags_select".
 */
export interface WhatsOnSubTagsSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero?: {
    title?: string | null;
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
  };
  info?:
    | {
        hexCode?: string | null;
        title?: string | null;
        richTextEditor?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  awards?: {
    title?: string | null;
    mediaWithLink?:
      | {
          media?: (number | null) | Media;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    media?:
      | {
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  kinnestMarquee?: {
    media?:
      | {
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  hero?: {
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
    title?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  contactBg?: (number | null) | Media;
  contactBgMobile?: (number | null) | Media;
  contactSubject?: string[] | null;
  accordion?:
    | (
        | {
            title?: string | null;
            columns?:
              | {
                  title?: string | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doubleColumn';
          }
        | {
            title?: string | null;
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttonText?: string | null;
            link?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleColumn';
          }
      )[]
    | null;
  email?: string | null;
  tel?: string | null;
  kinnestGroup?: string | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    line?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  announcementShow?: boolean | null;
  announcement?: {
    format?: ('square' | 'vertical' | 'landscape') | null;
    media?: (number | null) | Media;
    link?: string | null;
  };
  hero?: {
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
    title?: string | null;
  };
  motto?:
    | {
        text?: string | null;
        shape?: ('hexagon' | 'circle' | 'square') | null;
        id?: string | null;
      }[]
    | null;
  about?: {
    title?: string | null;
    description?: string | null;
    stickyNotes?:
      | {
          /**
           * Recommended aspect ratio: 1.4326
           */
          media?: (number | null) | Media;
          shape?: ('square' | 'circle' | 'heart') | null;
          text?: string | null;
          bgColor?: string | null;
          textColor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  peopleOfTheCommons?: {
    title?: string | null;
    cards?:
      | {
          media?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  flexibleSectionShow?: boolean | null;
  flexibleSection?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        bgColor?: string | null;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  whatAreYouInTheMoodFor?: {
    titleLineOne?: string | null;
    titleLineTwo?: string | null;
    preSentence?: string | null;
    preSentenceMobile?: string | null;
    lifestyles?: (number | Lifestyle)[] | null;
  };
  membership?:
    | {
        title?: string | null;
        description?: string | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        button?: {
          text?: string | null;
          link?: string | null;
        };
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  bingo?: {
    title?: string | null;
    grid?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  title?: string | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-rental-page".
 */
export interface VenueRentalPage {
  id: number;
  /**
   * One group per branch (3 total).
   */
  branchGroups?:
    | {
        branch: number | Branch;
        mediaGallery?: (number | Media)[] | null;
        bgColor?: string | null;
        textColor?: string | null;
        buttonColor?: string | null;
        /**
         * If enabled, the button text will be white on hover. Cannot be selected with dark brown hover text.
         */
        buttonWhiteTextOnHover?: boolean | null;
        /**
         * If enabled, the button text will be dark brown on hover. Cannot be selected with white hover text.
         */
        buttonDarkBrownTextOnHover?: boolean | null;
        title?: string | null;
        cta?: {
          text?: string | null;
          desc?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors-page".
 */
export interface VendorsPage {
  id: number;
  title?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on-page".
 */
export interface WhatsOnPage {
  id: number;
  hero?: {
    backgroundMedia?: (number | null) | Media;
    mobileBackgroundMedia?: (number | null) | Media;
    title?: string | null;
  };
  club?: {
    title?: string | null;
    mainTag?: (number | null) | WhatsOnMainTag;
  };
  allEventsAndWorkshops?: {
    title?: string | null;
    description?: string | null;
    mainTag?: (number | WhatsOnMainTag)[] | null;
    background?: string | null;
    eventArchiveBackground?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
      };
  info?:
    | T
    | {
        hexCode?: T;
        title?: T;
        richTextEditor?: T;
        media?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        title?: T;
        mediaWithLink?:
          | T
          | {
              media?: T;
              link?: T;
              id?: T;
            };
        media?:
          | T
          | {
              media?: T;
              id?: T;
            };
      };
  kinnestMarquee?:
    | T
    | {
        media?:
          | T
          | {
              media?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
        title?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  contactBg?: T;
  contactBgMobile?: T;
  contactSubject?: T;
  accordion?:
    | T
    | {
        doubleColumn?:
          | T
          | {
              title?: T;
              columns?:
                | T
                | {
                    title?: T;
                    richText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        singleColumn?:
          | T
          | {
              title?: T;
              richText?: T;
              buttonText?: T;
              link?: T;
              id?: T;
              blockName?: T;
            };
      };
  email?: T;
  tel?: T;
  kinnestGroup?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        line?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  announcementShow?: T;
  announcement?:
    | T
    | {
        format?: T;
        media?: T;
        link?: T;
      };
  hero?:
    | T
    | {
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
        title?: T;
      };
  motto?:
    | T
    | {
        text?: T;
        shape?: T;
        id?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
        stickyNotes?:
          | T
          | {
              media?: T;
              shape?: T;
              text?: T;
              bgColor?: T;
              textColor?: T;
              id?: T;
            };
      };
  peopleOfTheCommons?:
    | T
    | {
        title?: T;
        cards?:
          | T
          | {
              media?: T;
              title?: T;
              description?: T;
              link?: T;
              id?: T;
            };
      };
  flexibleSectionShow?: T;
  flexibleSection?:
    | T
    | {
        title?: T;
        description?: T;
        bgColor?: T;
        media?: T;
        id?: T;
      };
  whatAreYouInTheMoodFor?:
    | T
    | {
        titleLineOne?: T;
        titleLineTwo?: T;
        preSentence?: T;
        preSentenceMobile?: T;
        lifestyles?: T;
      };
  membership?:
    | T
    | {
        title?: T;
        description?: T;
        richText?: T;
        button?:
          | T
          | {
              text?: T;
              link?: T;
            };
        media?: T;
        id?: T;
      };
  bingo?:
    | T
    | {
        title?: T;
        grid?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T;
  richText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-rental-page_select".
 */
export interface VenueRentalPageSelect<T extends boolean = true> {
  branchGroups?:
    | T
    | {
        branch?: T;
        mediaGallery?: T;
        bgColor?: T;
        textColor?: T;
        buttonColor?: T;
        buttonWhiteTextOnHover?: T;
        buttonDarkBrownTextOnHover?: T;
        title?: T;
        cta?:
          | T
          | {
              text?: T;
              desc?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors-page_select".
 */
export interface VendorsPageSelect<T extends boolean = true> {
  title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whats-on-page_select".
 */
export interface WhatsOnPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundMedia?: T;
        mobileBackgroundMedia?: T;
        title?: T;
      };
  club?:
    | T
    | {
        title?: T;
        mainTag?: T;
      };
  allEventsAndWorkshops?:
    | T
    | {
        title?: T;
        description?: T;
        mainTag?: T;
        background?: T;
        eventArchiveBackground?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}